services:
  pegasus-cloud-iamserver:
    profiles:
      - ${IAM_DISABLE:-}    
    image: golang:1.22.4-alpine
    tty: true
    container_name: iam-server
    networks:
      pegasus-cloud-network:
        ipv4_address: 172.40.100.0
    working_dir: /home/${IAM_FOLDER_NAME}
    environment:
      - GOPROXY=${GOPROXY}
    volumes:
      - ${PWD}/..:/home
      - pegasus-cloud-eventpublishplugin:/var/lib/ASUS/EventPublishPlugin
      - ${PWD}/docker-compose/etc/PegasusIAM.yaml:/mnt/PegasusIAM.yaml
    entrypoint:
      - "sh"
      - "-c"
      - |-
        apk add make libc6-compat && \
        rm -rf tmp/* && \
        make RELEASE_MODE=prod go-build && \
        cp tmp/* /PegasusIAM && \
        /PegasusIAM serve -c /mnt/PegasusIAM.yaml
    ports:
      # - "3891:3891" # ldap
      # - "5051:5051" # grpc
      - "8084:8084" # http
    restart: on-failure

  pegasus-cloud-iamserver-release:
    profiles:
      - ${IAM_RELEASE_DISABLE:-}
    image: ociscloud/iam:1.8.3
    tty: true
    container_name: iam-server-release
    networks:
      pegasus-cloud-network:
        ipv4_address: 172.40.100.1
    volumes:
      - ${PWD}/docker-compose/etc/iam.yaml:/mnt/iam.yaml
      - pegasus-cloud-eventpublishplugin:/var/lib/ASUS/EventPublishPlugin
      - pegasus-cloud-iam-sock:/run
    command: ["/PegasusIAM","serve","-c","/mnt/iam.yaml"]
    ports:
      - "8084:8084" # http
    restart: on-failure

networks:
  pegasus-cloud-network:
    external: true
    name: pegasus-cloud-network

volumes:  
  pegasus-cloud-iam-sock:
    name: pegasus-cloud-iam-sock  
  pegasus-cloud-eventpublishplugin:
    name: pegasus-cloud-eventpublishplugin
    external: true
