version: "2"
services:
  pegasus-cloud-vrm:
    image: ociscloud/golang:1.22.4-${PLATFORM:-ubuntu-amd64}
    container_name: vrm-server
    networks:
      pegasus-cloud-network:
        ipv4_address: 172.40.120.0
    working_dir: /home/${SERVICE_FOLDER_NAME}
    environment:
      - GOPROXY=${GOPROXY}
    volumes:
      - ${PWD}/..:/home
      - pegasus-cloud-eventpublishplugin:/var/lib/ASUS/EventPublishPlugin
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "5109:5109" # http
      - "8109:8109" # http
    privileged: true
networks:
  pegasus-cloud-network:
    external: true
    name: pegasus-cloud-network
volumes:
  pegasus-cloud-eventpublishplugin:
    name: pegasus-cloud-eventpublishplugin
    external: true
