services:
  pegasus-cloud--vrm-swagger:
    profiles:
      - ${SWAGGER_DISABLE:-}
    image: swaggerapi/swagger-ui:v5.20.2
    container_name: swagger-ui-vrm
    volumes:
      - ${PWD}/..:/home
    environment:
      - SWAGGER_JSON=/home/virtualregistrymanagement/swagger.yaml
    networks:
      pegasus-cloud-network:
        ipv4_address: 172.40.206.0
    ports:
      - "8080:8080"

  pegasus-cloud-iam-swagger:
    profiles:
      - ${SWAGGER_DISABLE:-}
    image: swaggerapi/swagger-ui:v5.20.2
    container_name: swagger-ui-iam
    volumes:
      - ${PWD}/..:/home
    environment:
      - SWAGGER_JSON=/home/pegasusiam/swagger.yaml
    networks:
      pegasus-cloud-network:
        ipv4_address: 172.40.206.1
    ports:
      - "8081:8080"

networks:
  pegasus-cloud-network:
    external: true
    name: pegasus-cloud-network